name: stack-manager-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # prepare:
  #   runs-on: self-hosted
  #   outputs:
  #     commit: ${{ steps.prepare.outputs.commit }}
  #   steps:
  #     - uses: actions/checkout@v2
  #     - id: declare-variables
  #       run: |
  #         echo "::set-output name=commit::$(git log -1 --format='%H')"
          
  get-changed-files:
    runs-on: self-hosted
    outputs:
      changed-files: ${{ steps.get-changed-files.outputs.changed-file }}
    steps:
      - uses: actions/checkout@v2
      - id: get-changed-file
        run: |
          output=$(git log -1 --format='%H')
          git diff-tree --no-commit-id --name-only -r $output | grep -i -v -E '.github' | grep .yml
          echo "1"
          if [ $? == 0 ]
          then
            echo "::set-output name=changed-files::$(git diff-tree --no-commit-id --name-only -r $output | grep -i -v -E '.github' | grep .yml)"
            echo "Result: $(git diff-tree --no-commit-id --name-only -r $output | grep -i -v -E '.github' | grep .yml)"
  deploy:
    runs-on: self-hosted
    needs: get-changed-files
    steps:
      - name: down stack
        timeout-minutes: 3
        run: docker-compose -f ${{ needs.get-changed-files.outputs.changed-files }} down 
      - name: run stack
        timeout-minutes: 3
        run: docker-compose -f ${{ needs.get-changed-files.outputs.changed-files }} up 
