# This is a basic workflow to help you get started with Actions

name: stack-manager-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  get-changed-files:
    runs-on: self-hosted
    outputs:
      changed-files: ${{ steps.get-changed-file.outputs.changed-file }}
    steps:
      - id: get-changed-file
        run: echo "::set-output name=changed-file::$(git ls-files -c | grep -i -v -E '.github' | grep .yml)"
        if: 
  run-stack:
    # The type of runner that the job will run on
    runs-on: self-hosted
    needs: get-changed-files
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      # down stack before run new stack for prevent memory leak
      # down stack should be remove when using docker swarm
      - name: down stack
        timeout-minutes: 3
        run: docker-compose -f ${{ needs.get-changed-files.outputs.changed-files }} up 
      - name: run stack
        timeout-minutes: 3
        run: docker-compose -f ${{ needs.get-changed-files.outputs.changed-files }} up 
