name: stack-manager-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: set enviroment variables
        run: |
          export DUMMY_TEXT=${{ secrets.DUMMY_TEXT }}
      - name: deploy stack
        timeout-minutes: 5
        run: |
          set -ex
          for item in $(git diff HEAD^ --name-only | grep -oP '^([A-z0-9-]+)(?=/)' | uniq); do
            docker stack deploy --compose-file ${item}/stack.yml --prune --with-registry-auth ${item}
          done
